tl-its-umich-edu/canvas

- sectionsUtilityTool/.gitignore
- sectionsUtilityTool/pom.xml
- sectionsUtilityTool/src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
- sectionsUtilityTool/src/main/resources/log4j.properties
- sectionsUtilityTool/src/main/webapp/WEB-INF/web.xml
- sectionsUtilityTool/src/main/webapp/index.vm
- sectionsUtilityTool/src/main/webapp/templates/sections.vm
Added  the sectionUtilityTool Hello world application
> Intial check-in

- sectionsUtilityTool/src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
> TLUNIZIN-403 added wiring for doPut() in servlet

- sectionsUtilityTool/src/main/webapp/assets/js/utils.js
- sectionsUtilityTool/src/main/webapp/help.html
- sectionsUtilityTool/src/main/webapp/index.html
https://jira.it.umich.edu/browse/TLUNIZIN-411
This follows (and borrows from) models used in Qualtrics & GDrive LTI integrations - opening a new window with the help contents.
Reviewers: @dovek @lsloan
> TLUNIZIN-411 - add placeholder for help documentation

- sectionsUtilityTool/src/main/webapp/index.html
https://jira.it.umich.edu/browse/TLUNIZIN-412
Reviewers: @dovek @lsloan
> TLUNIZIN-412 - bind sortable sections to section model

- sectionsUtilityTool/src/main/webapp/assets/css/custom_style.css
- sectionsUtilityTool/src/main/webapp/assets/js/controllers/controllers.js
- sectionsUtilityTool/src/main/webapp/assets/js/utils.js
- sectionsUtilityTool/src/main/webapp/index.html
This pull request involves functionality to enable ServiceDesk to cross list courses belonging to different instructors. It can be seen in test server (see https://jira.it.umich.edu/browse/TLUNIZIN-397 for that info)
Reviewers: @dlhaines @dovek @lsloan @zqian @bkirschn
> Tlunizin 397

- sectionsUtilityTool/src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Reviewers: @bkirschn @dlhaines
> TLUNIZIN-347 logging the API request in servlet

- sectionsUtilityTool/src/main/webapp/assets/js/controllers/controllers.js
> TLUNIZIN-430 - change default page size to 200 for course lists (no code review needed)

- sectionsUtilityTool/src/main/webapp/assets/js/controllers/controllers.js
- sectionsUtilityTool/src/main/webapp/assets/js/utils.js
- sectionsUtilityTool/src/main/webapp/index.html
This is in order to change the "Crosslist" button to a "Done" button after a crosslist POST
> TLUNIZIN-409 - use deferred array to signal end of multiple posts

- sectionsUtilityTool/README.md
- sectionsUtilityTool/src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java
- sectionsUtilityTool/src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
- sectionsUtilityTool/src/main/resources/sectiontool.properties
- sectionsUtilityTool/src/main/webapp/assets/js/controllers/controllers.js
- sectionsUtilityTool/src/main/webapp/assets/js/utils.js
https://jira.it.umich.edu/browse/TLUNIZIN-423
As a step toward who can access the sections tool we have the user to authenticate and be authorized to access our tool. To add to it we will be checking only certain api call the tools uses are processed by servlet and restrict others.
Reviewers: @zqian @dlhaines 
Review by :end of 03/17/15
> TLUNIZIN-436 only allow a particular canvas api and not everything

- sectionsUtilityTool/.gitignore
- sectionsUtilityTool/build.sh
- sectionsUtilityTool/configuration-files.txt
- sectionsUtilityTool/src/main/resources/sectionsToolPropsSecure.properties.template
Reviewers:@dlhaines @lsloan 
Optional:@bkirschn
> Tlunizin 423

- sectionsUtilityTool/src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java
> TLUNIZIN-347 Adding session info with the uniqname in logs

- sectionsUtilityTool/src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
@dlhaines trello Codereview Request https://trello.com/c/wDXc9kH1/41-tlunizin-438
> TL-438 add response time from canvas info to logs

- sectionsUtilityTool/src/main/webapp/assets/js/utils.js
for 
https://jira.it.umich.edu/browse/TLUNIZIN-476
> TLUNIZIN-476 - send service center user to ServiceLink KB

- sectionsUtilityTool/src/main/webapp/assets/js/controllers/controllers.js
- sectionsUtilityTool/src/main/webapp/assets/js/factories/factories.js
- sectionsUtilityTool/src/main/webapp/assets/js/utils.js
- sectionsUtilityTool/src/main/webapp/index.html
for https://jira.it.umich.edu/browse/TLUNIZIN-464
@pushyamig - this is ready to be merged...
> TLUNIZIN-464 - some loose ends, see Jira for details

- SIS_import/sis_set_url.rb
major changes include:
1. handling of Canvas and ESB API call limit
2. handling of Canvas API call paging
3. removed the Canvas API call to "#{$canvasUrl}/api/v1/sections/#{sectionValue}", getting section information from the "#{$canvasUrl}/api/v1/courses/#{courseId}/sections" call instead.
> issue_44 handling Canvas paging and API threshold

- practiceCourseGenerator/build.sh
- practiceCourseGenerator/practiceCourseGenerator.py
Due Date: 5/1/2015
@lsloan 
@bkirschn
> Tlunizin 470 (attempt 2)

- practiceCourseGenerator/README.md
- practiceCourseGenerator/practiceCourseGenerator.py
Due Date: 5/6/2015
@lsloan 
@bkirschn
> TLUNIZIN-516 Update practiceCourseGenerator script with properties file inputs

- practiceCourseGenerator/practiceCourseGenerator.py
> TLUNIZIN-516 Bug fix for user missing first or last name.

- NotificationPreferencesReportGenerator/NotificationPreferencesReportGenerator.py
- NotificationPreferencesReportGenerator/README
- NotificationPreferencesReportGenerator/README.md
- NotificationPreferencesReportGenerator/checkedFrequencies.txt
- NotificationPreferencesReportGenerator/checkedNotifications.txt
> TLUNIZIN-437 - Notification Preference Report Generator

- SIS_import/sis_set_url.rb
added timestamp to the ESB error log messages
> issue_50:  use @canvasUrl in the error message subject line; 

- SIS_import/sis_set_url.rb
- SIS_import/sis_upload.rb
- SIS_import/utils.rb
> issue_57 handle possible nil or empty value of string prior to JSON.parse

- SIS_import/sis_upload.rb
created method to create instructor sandbox site, and add instructor to the site.
> TLUNIZIN-514 added methods to create instructor sandbox sites

- SIS_import/sis_upload.rb
update the required gem from "URI" to "uri"
> TLUNIZIN-514 changed the required gem from URI to uri

- SIS_import/sis_upload.rb
Parse the upload result json, and find whether there is a "processing_warnings" element value. Include those values in the alert email message.
> TLUNIZIN-548 send email when there is SIS upload warnings

- SIS_import/sis_set_url.rb
- SIS_import/sis_upload.rb
- SIS_import/utils.rb
added the Canvas API throttling mechanism to SIS upload process
> Tlunizin-631 SIS Upload fails silently while creating practice sites

- SIS_import/sis_instructor_practice_course.rb
- SIS_import/sis_set_url.rb
- SIS_import/sis_upload.rb
- SIS_import/utils.rb
separate the sandbox sites creation routine into different file;
improve logger logging messages.
> Tlunizin-596 Modify sis upload script so that practice courses are created in the Practice Course sub-account

- SIS_import/sis_set_url.rb
TLUNIZIN-690 removed a unnecessary logging line.
> TLUNIZIN-690 remove a verbose logging line

- SIS_import/sis_set_url.rb
- SIS_import/sis_upload.rb
- SIS_import/utils.rb
make sure the call count number is updated properly after each API call
> TLUNIZIN-690 fixed the problem with handling API call throttling 

- SIS_import/sis_upload.rb
workflow_status is a better indicator of the upload progress, instead of the progress field
> TLUNIZIN-725 workflow_status is a better indicator of the upload progress

- NotificationPreferencesReportGenerator/README.md
- NotificationPreferencesReportGenerator/getStudentsFromPublishedCourses.py
Added the script which creates the users.txt file.  Modified the readme.md file for the notification preferences sub-directory to reflect using this script.
> modified doc and added script to generate users file.

- SIS_import/Dockerfile
- SIS_import/sis_set_url.rb
- SIS_import/test/settings.sh
- SIS_import/test/test_API.sh
- SIS_import/test/test_esb.rb
> TLPSO-432 This is code for switching to ESB new IBM API Manager

- SIS_import/utils.rb
from error to warn for Canvas API returned json parsing exception
> issue_120 change the log level 

- SIS_import/.env_example
- SIS_import/rclone_setup.sh
- SIS_import/sis_set_url.rb
- SIS_import/sis_upload.rb
> issue_125 added an env variable as aws_s3_bucket

- SIS_import/Dockerfile
- revert back the changes made to rclone inside Dockerfile (#138)
- added the flag of --force-architecture to make build successful with Apple AMD
> issue_143 
